In [2]:
import numpy as np

In [3]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [4]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.zeros(23)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [13]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [15]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [16]:
np.linspace(0,10,2)

array([  0.,  10.])

In [17]:
np.linspace(0,10,5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [19]:
np.random.rand(5)

array([ 0.18721091,  0.57345037,  0.6147674 ,  0.7917835 ,  0.73756817])

In [20]:
np.random.rand(5) * 1000

array([ 537.19293618,  559.93051791,  577.88278933,  303.9528663 ,
        667.78505448])

In [21]:
np.random.rand(5,2,3)

array([[[ 0.34035364,  0.9095282 ,  0.37796811],
        [ 0.15082749,  0.50238208,  0.4533954 ]],

       [[ 0.20558834,  0.87075424,  0.48383446],
        [ 0.79990283,  0.25981558,  0.32953433]],

       [[ 0.65979754,  0.75248804,  0.97671794],
        [ 0.23500702,  0.19107454,  0.10019938]],

       [[ 0.52814707,  0.80067514,  0.02477809],
        [ 0.89521714,  0.42603564,  0.05865704]],

       [[ 0.8134918 ,  0.15981133,  0.46956376],
        [ 0.77198274,  0.16659971,  0.12367917]]])

In [22]:
np.random.randn(5)

array([ 0.21300567,  0.66136423, -0.74381647,  1.06461341,  0.90458525])

In [26]:
np.random.randint(0,100,15)

array([34, 91, 26, 24, 34, 96, 73, 20, 81, 70,  3, 70, 73, 14, 55])

In [27]:
arr = np.random.rand(25)

In [28]:
arr

array([ 0.92454714,  0.46179878,  0.85589064,  0.465245  ,  0.20664639,
        0.93079027,  0.08208175,  0.3693507 ,  0.95323186,  0.64429428,
        0.0057902 ,  0.19148199,  0.19196982,  0.59939531,  0.9804676 ,
        0.81145917,  0.74026733,  0.89948268,  0.67598121,  0.64164172,
        0.8612544 ,  0.60395899,  0.53840846,  0.65059495,  0.2176695 ])

In [29]:
arr.reshape((5,5))

array([[ 0.92454714,  0.46179878,  0.85589064,  0.465245  ,  0.20664639],
       [ 0.93079027,  0.08208175,  0.3693507 ,  0.95323186,  0.64429428],
       [ 0.0057902 ,  0.19148199,  0.19196982,  0.59939531,  0.9804676 ],
       [ 0.81145917,  0.74026733,  0.89948268,  0.67598121,  0.64164172],
       [ 0.8612544 ,  0.60395899,  0.53840846,  0.65059495,  0.2176695 ]])

In [30]:
arr = arr.reshape((5,5))

In [31]:
arr 

array([[ 0.92454714,  0.46179878,  0.85589064,  0.465245  ,  0.20664639],
       [ 0.93079027,  0.08208175,  0.3693507 ,  0.95323186,  0.64429428],
       [ 0.0057902 ,  0.19148199,  0.19196982,  0.59939531,  0.9804676 ],
       [ 0.81145917,  0.74026733,  0.89948268,  0.67598121,  0.64164172],
       [ 0.8612544 ,  0.60395899,  0.53840846,  0.65059495,  0.2176695 ]])

In [32]:
arr.shape

(5, 5)

In [33]:
arr.max()

0.98046759931970617

In [34]:
arr.min()

0.0057902032642753731

In [35]:
arr.argmax()

14

In [36]:
arr.argmin()

10